# Define the columns you want to select
selected_columns = ["SEED", "W", "ADJOE", "ADJDE", "BARTHAG", "EFG_O", "EFG_D", "TOR", "TORD", "ORB", "DRB", "FTR", "FTRD", "2P_O", "2P_D", "3P_O", "3P_D", "ADJ_T"]


featuer used last time:

features_used = ["Wins", "ADJOE", "ADJDE", "BARTHAG", "EFG%", "EFG%D",
                 "TOR", "TORD", "ORB", "DRB", "FTR", "FTRD", "2P%",
                 "2P%D", "3P%", "3P%D", "ADJ T.", "SEED"]


Feature ranks
["W", "ADJOE_rank", "ADJDE_rank", "BARTHAG_rank", "EFG%_rank", "EFGD%_rank",
"TOR_rank", "TORD_rank", "ORB_rank", "DRB_rank", "FTR_rank", "FTRD_rank", "2P%_rank",
"2P%D_rank", "3P%_rank", "3P%D_rank", "ADJ T._rank", "SEED"]

In [84]:
using CSV, DataFrames

filepath = "/mnt/chromeos/removable/memexpand/basketball_data/tournament_teams_by_round/cbb08_24_tourn_all.csv"
df = CSV.read(filepath, DataFrame)
filepath_test = "/mnt/chromeos/removable/memexpand/basketball_data/clean data all teams/cbb2025.csv"
df_test = CSV.read(filepath_test, DataFrame)

68×46 DataFrame
 Row │ RK     TEAM            CONF     G      WAB         POSTSEASON  SEED   W ⋯
     │ Int64  String31        String7  Int64  String15    Int64       Int64  I ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │    95  Akron           MAC         34  -1.7\n63             0     13    ⋯
   2 │     5  Alabama         SEC         33  #ERROR!              0      2
   3 │   275  Alabama St.     SWAC        35  -10.1\n200           0     16
   4 │   243  American        Pat         34  -8.2\n165            0     16
   5 │     9  Arizona         B12         34  #ERROR!              0      4    ⋯
   6 │    42  Arkansas        SEC         33  #ERROR!              0     10
   7 │     3  Auburn          SEC         33  #ERROR!              0      1
   8 │    14  BYU             B12         33  #ERROR!              0      6
   9 │    27  Baylor          B12         33  #ERROR!              0      9    ⋯
  10 │   153  Bryant          AE          34  -7.1\n141            0     15
  11 │    20  Clemson         ACC         33  #ERROR!              0      5
  ⋮  │   ⋮          ⋮            ⋮       ⋮        ⋮           ⋮         ⋮      ⋱
  59 │    48  UC San Diego    BW          34  #ERROR!              0     12
  60 │    25  UCLA            B10         32  #ERROR!              0      7    ⋯
  61 │   108  UNC Wilmington  CAA         34  -3.2\n80             0     14
  62 │    50  Utah St.        MWC         33  #ERROR!              0     10
  63 │    31  VCU             A10         34  #ERROR!              0     11
  64 │    41  Vanderbilt      SEC         32  #ERROR!              0     10    ⋯
  65 │    12  Wisconsin       B10         35  #ERROR!              0      3
  66 │   143  Wofford         SC          34  -9.7\n193            0     15
  67 │    37  Xavier          BE          32  #ERROR!              0     11
  68 │    78  Yale            Ivy         29  -2.7\n73             0     13    ⋯
                                                  39 columns and 47 rows omitted

current features

selected_columns = [
    "BARTHAG",
    #"WINS",
    "SEED",
    "ADJOE",
    "ADJDE",
    "2P%",  # Assuming 2P% is stored as 2P_O in your dataset
    "3P%",  # Assuming 3P% is stored as 3P_O in your dataset
    #"EFG%", # Assuming EFG% is stored as EFG_O in your dataset
    #"FTR",
    #"TORD"
    "POSTSEASON"
]

selected_columns_a = [
    "BARTHAG",
    #"WINS",
    "SEED",
    "ADJOE",
    "ADJDE",
    "2P%",  # Assuming 2P% is stored as 2P_O in your dataset
    "3P%",  # Assuming 3P% is stored as 3P_O in your dataset
    #"EFG%", # Assuming EFG% is stored as EFG_O in your dataset
    #"FTR",
    #"TORD"
    "TEAM"
]

In [86]:
selected_columns = ["SEED","ADJOE_rank", "ADJDE_rank", "BARTHAG_rank", "EFG%_rank", "EFGD%_rank", "TOR_rank", "TORD_rank","ORB_rank","DRB_rank","POSTSEASON"]

selected_columns_a = ["SEED","ADJOE_rank", "ADJDE_rank", "BARTHAG_rank", "EFG%_rank", "EFGD%_rank", "TOR_rank", "TORD_rank","ORB_rank","DRB_rank", "TEAM"]



11-element Vector{String}:
 "SEED"
 "ADJOE_rank"
 "ADJDE_rank"
 "BARTHAG_rank"
 "EFG%_rank"
 "EFGD%_rank"
 "TOR_rank"
 "TORD_rank"
 "ORB_rank"
 "DRB_rank"
 "TEAM"

In [87]:
using CSV, DataFrames

# Split into training (2008-2023) and testing (2024) dataframes
df_train = df[df.YEAR .!= 2024, Cols(vcat("YEAR", selected_columns))]
#df_test = df[df.YEAR .== 2024, Cols(vcat("YEAR", selected_columns_a))]
select!(df_test, selected_columns_a)


# Remove specific columns from the training set if needed
# df_train = select!(df_train, Not(:WAB, :TEAM, :CONF, :G))
df_train = select!(df_train, Not(:YEAR))
#df_test = select!(df_test, Not(:YEAR))
#run the whole dataframe
#df_train = df[df.YEAR .!= 2024, Not([:WAB, :TEAM, :CONF, :G])]
#df_test = df[df.YEAR .== 2024, Not([:WAB, :TEAM, :CONF, :G])]

# Print the sizes of the resulting dataframes
println("Training set size: ", size(df_train))
println("Testing set size: ", size(df_test))


Training set size: (1011, 11)
Testing set size: (68, 11)


In [89]:
using DataFrames
using MLJ
using MLJBase: transform

# Check if "POSTSEASON" exists in df_train
if "POSTSEASON" in names(df_train)
    y = df_train.POSTSEASON
else
    println("Column 'POSTSEASON' does not exist in df_train.")
    # Handle the case where "POSTSEASON" is not present
    # For example, you might need to create or load it from another source
end

# Remove "POSTSEASON" from selected_columns if it's present
selected_columns_without_postseason = filter(col -> col != "POSTSEASON", selected_columns)

# Select columns from df_train, excluding "POSTSEASON"
X = select(df_train, selected_columns_without_postseason)

println("X size: $(size(X))")
if "POSTSEASON" in names(df_train)
    println("y length: $(length(y))")
end

# Convert X to matrix
# Define the feature set used for training and prediction
selected_columns_B = ["ADJOE_rank", "ADJDE_rank", "BARTHAG_rank", "EFG%_rank", "EFGD%_rank", "TOR_rank", "TORD_rank","ORB_rank","DRB_rank"]

# Ensure X_matrix contains exactly these columns in the correct order
X_matrix = select(df_train, selected_columns_B)

# Ensure y is a vector of integers if it exists
if "POSTSEASON" in names(df_train)
    y_vector = convert(Vector{Int64}, y)
    
    # Print class distribution
    println("Original class distribution:")
    for class in sort(unique(y_vector))
        count = sum(y_vector .== class)
        println("Class $class: $count samples")
    end
end

X size: (1011, 10)
y length: 1011
Original class distribution:
Class 1: 531 samples
Class 2: 240 samples
Class 3: 120 samples
Class 4: 60 samples
Class 5: 30 samples
Class 6: 15 samples
Class 7: 15 samples


In [90]:
using DataFrames
using Random
Random.seed!(42)

function balanced_oversampling(X::Matrix, y::Vector, target_count::Int)
    # Get unique classes
    classes = sort(unique(y))
    
    # Initialize arrays to hold oversampled data
    X_balanced = Matrix{Float64}(undef, 0, size(X, 2))
    y_balanced = Int64[]
    
    # Process each class
    for class in classes
        # Get indices for this class
        class_indices = findall(y .== class)
        class_count = length(class_indices)
        
        # Extract class data
        X_class = X[class_indices, :]
        y_class = y[class_indices]
        
        # If class already has enough samples, just take them all
        if class_count >= target_count
            # Optionally downsample if class is much larger than target
            if class_count > target_count
                sample_indices = randperm(class_count)[1:target_count]
                X_balanced = vcat(X_balanced, X_class[sample_indices, :])
                append!(y_balanced, y_class[sample_indices])
            else
                X_balanced = vcat(X_balanced, X_class)
                append!(y_balanced, y_class)
            end
        else
            # Need to oversample
            # Add all original samples
            X_balanced = vcat(X_balanced, X_class)
            append!(y_balanced, y_class)
            
            # Calculate how many more samples we need
            samples_needed = target_count - class_count
            
            # Generate random indices with replacement
            random_indices = rand(1:class_count, samples_needed)
            
            # Add the oversampled data
            X_balanced = vcat(X_balanced, X_class[random_indices, :])
            append!(y_balanced, y_class[random_indices])
        end
    end
    
    return X_balanced, y_balanced
end




balanced_oversampling (generic function with 1 method)

In [91]:
X_matrix = Matrix(X)
df_test_copy = copy(df_test)

X_test = select!(df_test_copy, Not(:TEAM))
X_test_matrix = Matrix(X_test)

68×10 Matrix{Int64}:
 13   62  182   95   31  110  137  174   76  136
  2    4   28    5   14   50  149  348   39  149
 16  282  247  275  325  163    4   86  228  225
 16  268  194  243  119  242  155  139  335   62
  4   10   30    9   83   73  108  212   19  107
 10   82   21   42   88   60  132  151  245   97
  1    1   12    3   26   10    6  155   51  211
  6    7   53   14    7  163  207  174   76   30
  9   17   56   27  135  196  103   81   22  250
 15  191  150  153  162   42  132  228   54  126
  5   26   16   20   63   86   75   41   65  185
 12   40   50   39   24   68  192  200  278   16
  8   16   93   36   28   60  174  287   22   62
  ⋮                        ⋮                 
  3    6   32    7   28   53   30  155   51  107
 14  161   70  101  214   29  330   50    6  287
 12   67   36   48   31   42    6    2  306  102
  7   27   19   25   80  156   88    5   90  149
 14   76  185  108  105  178   95  155   28   89
 10   14  153   50   20  231   95   37   43  211
 1

In [92]:
# Example usage:
X_balanced, y_balanced = balanced_oversampling(X_matrix, y_vector, 531)

# Convert back to DataFrames if needed
X_over_df = DataFrame(X_balanced, :auto)
y_over_df = DataFrame(:POSTSEASON => y_balanced)

# Print the new class distribution
println("\nAfter SMOTE oversampling:")
for class in sort(unique(y_balanced))
    count = sum(y_balanced .== class)
    println("Class $class: $count samples")
end


After SMOTE oversampling:
Class 1: 531 samples
Class 2: 531 samples
Class 3: 531 samples
Class 4: 531 samples
Class 5: 531 samples
Class 6: 531 samples
Class 7: 531 samples


In [93]:
using MLJ
import MLJ: fit!, predict, predict_mode, machine
using XGBoost
using MLJLIBSVMInterface
using DecisionTree
using Random
Random.seed!(42)

TaskLocalRNG()

In [94]:
# Define a function to evaluate each model individually
function evaluate_model(model, model_name, X, y, train_indices, test_indices)
    println("Evaluating $model_name...")
    model_machine = machine(model, X, y)
    MLJ.fit!(model_machine, rows=train_indices)
    y_pred = MLJ.predict_mode(model_machine, rows=test_indices)
    acc = accuracy(y_pred, y[test_indices])
    println("$model_name Accuracy: ", round(acc, digits=4))
    return model_machine
end

evaluate_model (generic function with 1 method)

In [95]:
# Load individual models
XGBoost_model = @load XGBoostClassifier pkg=XGBoost
forest_model = @load RandomForestClassifier pkg=DecisionTree
d_tree_model = @load DecisionTreeClassifier pkg=DecisionTree

# Define models with hyperparameters
boosting_model = XGBoost_model(num_round=10, max_depth=3)
forest_model = forest_model()
d_tree_model = d_tree_model()

import MLJXGBoostInterface ✔
import MLJDecisionTreeInterface ✔


[ Info: For silent loading, specify `verbosity=0`. 
[ Info: For silent loading, specify `verbosity=0`. 
[ Info: For silent loading, specify `verbosity=0`. 


import MLJDecisionTreeInterface ✔


DecisionTreeClassifier(
  max_depth = -1, 
  min_samples_leaf = 1, 
  min_samples_split = 2, 
  min_purity_increase = 0.0, 
  n_subfeatures = 0, 
  post_prune = false, 
  merge_purity_threshold = 1.0, 
  display_depth = 5, 
  feature_importance = :impurity, 
  rng = TaskLocalRNG())

In [96]:
X_test_matrix

68×10 Matrix{Int64}:
 13   62  182   95   31  110  137  174   76  136
  2    4   28    5   14   50  149  348   39  149
 16  282  247  275  325  163    4   86  228  225
 16  268  194  243  119  242  155  139  335   62
  4   10   30    9   83   73  108  212   19  107
 10   82   21   42   88   60  132  151  245   97
  1    1   12    3   26   10    6  155   51  211
  6    7   53   14    7  163  207  174   76   30
  9   17   56   27  135  196  103   81   22  250
 15  191  150  153  162   42  132  228   54  126
  5   26   16   20   63   86   75   41   65  185
 12   40   50   39   24   68  192  200  278   16
  8   16   93   36   28   60  174  287   22   62
  ⋮                        ⋮                 
  3    6   32    7   28   53   30  155   51  107
 14  161   70  101  214   29  330   50    6  287
 12   67   36   48   31   42    6    2  306  102
  7   27   19   25   80  156   88    5   90  149
 14   76  185  108  105  178   95  155   28   89
 10   14  153   50   20  231   95   37   43  211
 1

In [97]:
# Convert data to tables if needed
X_table = MLJ.table(X_balanced)
y_cat = categorical(y_balanced)
X_test_table = MLJ.table(X_matrix_test)

# Create train/test split
train, test = partition(eachindex(y_cat), 0.8, shuffle=true, rng=42)

([3178, 370, 1013, 979, 1101, 216, 331, 2301, 2455, 33  …  2258, 2263, 1458, 71, 1896, 1773, 373, 2878, 70, 482], [3602, 2265, 332, 1923, 1843, 3702, 3061, 3133, 2607, 1568  …  72, 3644, 2621, 2473, 662, 963, 3447, 3001, 2618, 1206])

In [98]:
# Define a function to evaluate each model individually
function evaluate_model(model, model_name, X, y, train_indices, test_indices)
    println("Evaluating $model_name...")
    model_machine = machine(model, X, y)
    MLJ.fit!(model_machine, rows=train_indices)
    y_pred = MLJ.predict_mode(model_machine, rows=test_indices)
    acc = accuracy(y_pred, y[test_indices])
    println("$model_name Accuracy: ", round(acc, digits=4))
    return model_machine
end

evaluate_model (generic function with 1 method)

In [99]:
# Evaluate individual models
println("Individual model performances:")
xgb_machine = evaluate_model(boosting_model, "XGBoost", X_table, y_cat, train, test)
rf_machine = evaluate_model(forest_model, "Random Forest", X_table, y_cat, train, test)
dt_machine = evaluate_model(d_tree_model, "Decision Tree", X_table, y_cat, train, test)

Individual model performances:
Evaluating XGBoost...


[ Info: Training machine(XGBoostClassifier(test = 1, …), …).
[ Info: XGBoost: starting training.
[ Info: [1]	train-mlogloss:1.61594114078317785
[ Info: [2]	train-mlogloss:1.44170167412866901
[ Info: [3]	train-mlogloss:1.30709032945850989
[ Info: [4]	train-mlogloss:1.20926078277180959
[ Info: [5]	train-mlogloss:1.12804281678509222
[ Info: [6]	train-mlogloss:1.07320544867204504
[ Info: [7]	train-mlogloss:1.00203845110329182
[ Info: [8]	train-mlogloss:0.95953508340719162


XGBoost Accuracy: 0.747

[ Info: [9]	train-mlogloss:0.91574316248848842
[ Info: [10]	train-mlogloss:0.87405543661630625
[ Info: Training rounds complete.



Evaluating Random Forest...


[ Info: Training machine(RandomForestClassifier(max_depth = -1, …), …).


Random Forest Accuracy: 0.926
Evaluating Decision Tree...
Decision Tree Accuracy: 0.9166

[ Info: Training machine(DecisionTreeClassifier(max_depth = -1, …), …).


trained Machine; caches model-specific representations of data
  model: DecisionTreeClassifier(max_depth = -1, …)
  args: 
    1:	Source @666 ⏎ Table{AbstractVector{Continuous}}
    2:	Source @831 ⏎ AbstractVector{Multiclass{7}}


In [100]:
# Fixed voting ensemble function for general models
function voting_ensemble(machines, X_data; rows=nothing, weights=nothing)
    # Get predictions (model-agnostic)
    preds = isnothing(rows) ? 
        [MLJ.predict_mode(mach, X_data) for mach in machines] :
        [MLJ.predict_mode(mach, X_data)[rows] for mach in machines]
    
    # Weight handling
    weights = isnothing(weights) ? 
        ones(length(machines))/length(machines) : 
        weights ./ sum(weights)
    
    # Voting logic
    all_classes = levels(preds[1])
    result = similar(preds[1])
    
    for i in eachindex(result)
        votes = Dict(cls => 0.0 for cls in all_classes)
        for (j, p) in enumerate(preds)
            votes[p[i]] += weights[j]
        end
        result[i] = argmax(votes)
    end
    
    return result
end


voting_ensemble (generic function with 1 method)

In [101]:
using MLJ

# Use a different name for your array of machines
my_machines = [
    machine(boosting_model, X_table, y_cat),
    #svm_mach,  # Use the already trained SVM machine directly
    machine(forest_model, X_table, y_cat),
    machine(d_tree_model, X_table, y_cat)
]

# Fit all other machines on the training data
for m in my_machines
    #if m != svm_mach  # Skip the already trained SVM
        fit!(m, rows=train)
    #end
end

[ Info: Training machine(XGBoostClassifier(test = 1, …), …).
[ Info: XGBoost: starting training.
[ Info: [1]	train-mlogloss:1.61594114078317785
[ Info: [2]	train-mlogloss:1.44170167412866901
[ Info: [3]	train-mlogloss:1.30709032945850989
[ Info: [4]	train-mlogloss:1.20926078277180959
[ Info: [5]	train-mlogloss:1.12804281678509222
[ Info: [6]	train-mlogloss:1.07320544867204504


[ Info: [7]	train-mlogloss:1.00203845110329182
[ Info: [8]	train-mlogloss:0.95953508340719162
[ Info: [9]	train-mlogloss:0.91574316248848842
[ Info: [10]	train-mlogloss:0.87405543661630625
[ Info: Training rounds complete.
[ Info: Training machine(RandomForestClassifier(max_depth = -1, …), …).
[ Info: Training machine(DecisionTreeClassifier(max_depth = -1, …), …).


In [102]:
using MLJ, Tables, Statistics, CategoricalArrays

function voting_ensemble(machines, X_data; rows=nothing, weights=nothing)
    # Convert to matrix, subset, then back to table
    X_matrix = Tables.matrix(X_data)
    X_subset = isnothing(rows) ? X_matrix : X_matrix[rows, :]
    X_table = Tables.table(X_subset)
    
    # Get predictions from each model
    preds = [MLJ.predict(mach, X_table) for mach in machines]
    
    # Ensure weights are provided or use equal weights
    if isnothing(weights)
        weights = ones(length(machines)) / length(machines)
    else
        weights = weights ./ sum(weights) # Normalize weights
    end
    
    # Combine predictions
    if all(pred -> eltype(pred) <: UnivariateFinite, preds)
        # Working with probability distributions
        combined_probs = sum(p .* w for (p, w) in zip(preds, weights))
        return mode.(combined_probs)
    else
        # Working with direct class predictions
        n_instances = length(first(preds))
        final_preds = Vector{Any}(undef, n_instances)
        
        for i in 1:n_instances
            votes = Dict{Any, Float64}()
            for (model_idx, pred) in enumerate(preds)
                class = pred[i]
                if class isa CategoricalArrays.CategoricalValue
                    class = class.pool.levels[class.refs]
                end
                votes[class] = get(votes, class, 0.0) + weights[model_idx]
            end
            final_preds[i] = argmax(votes)
        end
        
        # Convert to categorical if all predictions are integers
        if all(x -> isa(x, Integer), final_preds)
            return categorical(final_preds)
        else
            return final_preds
        end
    end
end

voting_ensemble (generic function with 1 method)

In [103]:
# Make predictions using our custom voting ensemble
ensemble_preds = voting_ensemble(my_machines, X_table; rows=test)

# Convert predictions to categorical if necessary for comparison with true labels
ensemble_preds_cat = categorical(ensemble_preds)

# Calculate ensemble accuracy
ensemble_acc = accuracy(ensemble_preds_cat, y_cat[test])
println("\nCustom Voting Ensemble Accuracy: ", round(ensemble_acc, digits=4))


Custom Voting Ensemble Accuracy: 0.9139


In [104]:
# Try weighted voting based on individual model performance
model_accs = [
    accuracy(MLJ.predict_mode(xgb_machine; rows=test), y_cat[test]),
    # accuracy(MLJ.predict_mode(svm_machine; rows=test), y_cat[test]),  # Uncomment if using SVM
    accuracy(MLJ.predict_mode(rf_machine; rows=test), y_cat[test]),
    accuracy(MLJ.predict_mode(dt_machine; rows=test), y_cat[test])
]
println("\nModel accuracies for weighting:")
println("XGBoost: ", round(model_accs[1], digits=4))
# println("SVM: ", round(model_accs[2], digits=4))  # Uncomment if using SVM
println("Random Forest: ", round(model_accs[2], digits=4))  # Adjust index if not using SVM
println("Decision Tree: ", round(model_accs[3], digits=4))  # Adjust index if not using SVM


Model accuracies for weighting:
XGBoost: 0.747
Random Forest: 0.926
Decision Tree: 0.9166


----------

tournament simulation

In [105]:
X_test_float = Float64.(X_test)
ensemble_preds = voting_ensemble(my_machines, X_test_float; rows=1:size(X_test_float, 1))



68-element CategoricalArray{Int64,1,UInt32}:
 2
 2
 1
 1
 3
 1
 4
 2
 1
 1
 3
 1
 1
 ⋮
 4
 1
 1
 4
 1
 2
 1
 2
 5
 1
 1
 1

In [106]:
#@assert length(ensemble_preds) == nrow() "Number of predictions must match number of rows in df_test"
df_test[!, :ensemble_preds] = ensemble_preds
first(df_test, 5) # View the first 5 rows to confirm the new column


5×12 DataFrame
 Row │ SEED   ADJOE_rank  ADJDE_rank  BARTHAG_rank  EFG%_rank  EFGD%_rank  TOR ⋯
     │ Int64  Int64       Int64       Int64         Int64      Int64       Int ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │    13          62         182            95         31         110      ⋯
   2 │     2           4          28             5         14          50
   3 │    16         282         247           275        325         163
   4 │    16         268         194           243        119         242
   5 │     4          10          30             9         83          73      ⋯
                                                               6 columns omitted

In [107]:
df_test.adjoe_adjde_diff = df_test.ADJOE_rank - df_test.ADJDE_rank
first(df_test, 5)

5×13 DataFrame
 Row │ SEED   ADJOE_rank  ADJDE_rank  BARTHAG_rank  EFG%_rank  EFGD%_rank  TOR ⋯
     │ Int64  Int64       Int64       Int64         Int64      Int64       Int ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │    13          62         182            95         31         110      ⋯
   2 │     2           4          28             5         14          50
   3 │    16         282         247           275        325         163
   4 │    16         268         194           243        119         242
   5 │     4          10          30             9         83          73      ⋯
                                                               7 columns omitted

In [112]:
using DataFrames, CategoricalArrays

function simulate_single_elimination_tournament(df::DataFrame)
    predictions_df = copy(df)
    
    # Convert CategoricalArray to numeric if needed
    if isa(predictions_df.ensemble_preds, CategoricalArray)
        # Option 1: If the values represent numbers, convert to integers
        predictions_df.ensemble_preds = Int.(levelcode.(predictions_df.ensemble_preds))
        
        # Option 2: Alternatively, you could make the categorical array ordered
        # ordered!(predictions_df.ensemble_preds, true)
    end
    
    remaining_teams = collect(1:nrow(predictions_df))
    round_winners = []
    
    for round_number in 1:6
        println("Round $round_number:")
        if length(remaining_teams) == 1
            println("Winner: $(predictions_df[remaining_teams[1], :TEAM])")
            break
        end
        
        winners_this_round = []
        # Pair up teams for this round
        for i in 1:2:length(remaining_teams)
            if i + 1 > length(remaining_teams)
                # Handle odd number of teams - give a bye
                push!(winners_this_round, remaining_teams[i])
                println("$(predictions_df[remaining_teams[i], :TEAM]) gets a bye")
                continue
            end
            
            team1 = remaining_teams[i]
            team2 = remaining_teams[i + 1]
            
            # Determine the winner for this match
            if predictions_df[team1, :ensemble_preds] > predictions_df[team2, :ensemble_preds]
                winner = team1
            elseif predictions_df[team1, :ensemble_preds] < predictions_df[team2, :ensemble_preds]
                winner = team2
            else
                # If ensemble_preds are equal, compare adjoe_adjde_diff
                if predictions_df[team1, :adjoe_adjde_diff] > predictions_df[team2, :adjoe_adjde_diff]
                    winner = team1
                else
                    winner = team2
                end
            end
            
            push!(winners_this_round, winner)
            println("$(predictions_df[team1, :TEAM]) vs $(predictions_df[team2, :TEAM]): Winner: $(predictions_df[winner, :TEAM])")
        end
        
        push!(round_winners, winners_this_round)
        remaining_teams = winners_this_round
    end
    
    return round_winners
end


simulate_single_elimination_tournament (generic function with 1 method)

In [113]:
using DataFrames, CategoricalArrays

function reorder_dataframe(df_a, column_name, order_list)
    """
    Filters and reorders the rows of a DataFrame based on a specified column and order list.
    Parameters:
        df_a (DataFrame): The DataFrame to be filtered and reordered.
        column_name (Symbol or String): The name of the column used for filtering and reordering.
        order_list (Vector): The list of values specifying the desired order.
    Returns:
        DataFrame: The filtered and reordered DataFrame.
    """
    # Create a copy of the DataFrame
    df = copy(df_a)
    
    # Convert column_name to Symbol if it's a String
    col_sym = typeof(column_name) == String ? Symbol(column_name) : column_name
    
    # Ensure column_name exists in DataFrame
    if !(col_sym in propertynames(df))
        error("Column '$(col_sym)' does not exist in the DataFrame.")
    end
    
    # First filter the DataFrame to include only rows with values in order_list
    filtered_df = filter(row -> row[col_sym] in order_list, df)
    
    # Check if we found all teams in the dataframe
    found_teams = unique(filtered_df[:, col_sym])
    missing_teams = setdiff(order_list, found_teams)
    if !isempty(missing_teams)
        @warn "The following teams from order_list were not found in the DataFrame: $(missing_teams)"
    end
    
    # Create a dictionary mapping each value to its position in order_list
    order_dict = Dict(value => i for (i, value) in enumerate(order_list))
    
    # Sort the filtered DataFrame based on the order specified in order_list
    sorted_df = sort(filtered_df, col_sym, by = x -> get(order_dict, x, length(order_list) + 1))
    
    return sorted_df
end

# Example usage:
# reordered_df = reorder_dataframe(tourny, :Team, desired_order)
# println(reordered_df)

reorder_dataframe (generic function with 1 method)

using DataFrames

function first4_dataframe(df, column_name, teams_of_interest)
    # Filter the DataFrame where the specified column matches any of the teams of interest
    filtered_df = filter(row -> row[column_name] in teams_of_interest, df)
    return filtered_df
end

# Define the teams of interest for each DataFrame
MW_1_teams = ["Montana St.", "Grambling St."]
MW_2_teams = ["Virgina", "Colorado St."]
S_teams = ["Colorado", "Boise St."]
SW_teams = ["Wagner", "Howard"]

# Create DataFrames for each set of teams
first_MW_1 = first4_dataframe(df_test, :TEAM, MW_1_teams)
first_MW_2 = first4_dataframe(df_test, :TEAM, MW_2_teams)
first_S = first4_dataframe(df_test, :TEAM, S_teams)
first_SW = first4_dataframe(df_test, :TEAM, SW_teams)

# Simulate tournaments for each group
first_MW1_teams = simulate_single_elimination_tournament(first_MW_1)
first_south_teams = simulate_single_elimination_tournament(first_S)
first_MW2_teams = simulate_single_elimination_tournament(first_MW_2)
first_southwest_teams = simulate_single_elimination_tournament(first_SW)

In [114]:
# Define the teams for each region


south_teams = ["Auburn", "Alabama St.", "Louisville", "Creighton", "Michigan", "UC San Diego",
"Texas A&M", "Yale", "Mississippi", "North Carolina", "Iowa St.", "Lipscomb",
"Marquette", "New Mexico", "Michigan St.", "Bryant"]

South_df = reorder_dataframe(df_test, :TEAM, south_teams)
S_bracket = simulate_single_elimination_tournament(South_df)


Round 1:
Auburn vs Alabama St.: Winner: Auburn
Louisville vs Creighton: Winner: Louisville
Michigan vs UC San Diego: Winner: Michigan
Texas A&M vs Yale: Winner: Texas A&M
Mississippi vs North Carolina: Winner: Mississippi
Iowa St. vs Lipscomb: Winner: Iowa St.
Marquette vs New Mexico: Winner: New Mexico
Michigan St. vs Bryant: Winner: Michigan St.
Round 2:
Auburn vs Louisville: Winner: Auburn
Michigan vs Texas A&M: Winner: Michigan
Mississippi vs Iowa St.: Winner: Iowa St.
New Mexico vs Michigan St.: Winner: Michigan St.
Round 3:
Auburn vs Michigan: Winner: Auburn
Iowa St. vs Michigan St.: Winner: Michigan St.
Round 4:
Auburn vs Michigan St.: Winner: Michigan St.
Round 5:
Winner: Michigan St.


4-element Vector{Any}:
 Any[1, 3, 5, 7, 9, 11, 14, 15]
 Any[1, 5, 11, 15]
 Any[1, 15]
 Any[15]

In [119]:
mw_teams = ["Houston", "SIU Edwardsville", "Gonzaga", "Georgia", "Clemson", "McNeese St.",
"Purdue", "High Point", "Illinois", "Texas", "Kentucky", "Troy",
"UCLA", "Utah St.", "Tennessee", "Wofford"]

# Assuming reorder_dataframe function exists, set dataframes for each region
MW_df = reorder_dataframe(df_test, :TEAM, mw_teams)
MW_bracket = simulate_single_elimination_tournament(MW_df)


Round 1:
Houston vs SIU Edwardsville: Winner: Houston
Gonzaga vs Georgia: Winner: Gonzaga
Clemson vs McNeese St.: Winner: Clemson
Purdue vs High Point: Winner: Purdue
Illinois vs Texas: Winner: Illinois
Kentucky vs Troy: Winner: Kentucky
UCLA vs Utah St.: Winner: UCLA
Tennessee vs Wofford: Winner: Tennessee
Round 2:
Houston vs Gonzaga: Winner: Houston
Clemson vs Purdue: Winner: Clemson
Illinois vs Kentucky: Winner: Illinois
UCLA vs Tennessee: Winner: UCLA
Round 3:
Houston vs Clemson: Winner: Clemson
Illinois vs UCLA: Winner: UCLA
Round 4:
Clemson vs UCLA: Winner: UCLA
Round 5:
Winner: UCLA


4-element Vector{Any}:
 Any[1, 3, 5, 7, 9, 11, 13, 15]
 Any[1, 5, 9, 13]
 Any[5, 13]
 Any[13]

In [120]:
east_teams = ["Duke", "Mount St. Mary's", "Mississippi St.", "Baylor", "Oregon", "Liberty",
"Arizona", "Akron", "BYU", "VCU", "Wisconsin", "Montana",
"Saint Mary's", "Vanderbilt", "Alabama", "Robert Morris"]
              
E_df = reorder_dataframe(df_test, :TEAM, east_teams)
E_bracket = simulate_single_elimination_tournament(E_df)


Round 1:
Duke vs Mount St. Mary's: Winner: Duke
Mississippi St. vs Baylor: Winner: Mississippi St.
Oregon vs Liberty: Winner: Liberty
Arizona vs Akron: Winner: Arizona
BYU vs VCU: Winner: BYU
Wisconsin vs Montana: Winner: Wisconsin
Saint Mary's vs Vanderbilt: Winner: Vanderbilt
Alabama vs Robert Morris: Winner: Alabama
Round 2:
Duke vs Mississippi St.: Winner: Duke
Liberty vs Arizona: Winner: Arizona
BYU vs Wisconsin: Winner: Wisconsin
Vanderbilt vs Alabama: Winner: Alabama
Round 3:
Duke vs Arizona: Winner: Duke
Wisconsin vs Alabama: Winner: Wisconsin
Round 4:
Duke vs Wisconsin: Winner: Wisconsin
Round 5:
Winner: Wisconsin


4-element Vector{Any}:
 Any[1, 3, 6, 7, 9, 11, 14, 15]
 Any[1, 7, 11, 15]
 Any[1, 11]
 Any[11]

In [121]:
w_teams = ["Florida", "Norfolk St.", "Connecticut", "Oklahoma", "Memphis", "Colorado St.",
"Maryland", "Grand Canyon", "Missouri", "Drake", "UNC Wilmington", "Kansas",
"Arkansas", "St. John's", "Texas Tech", "Nebraska Omaha"]

W_df = reorder_dataframe(df_test, :TEAM, w_teams)
W_bracket = simulate_single_elimination_tournament(W_df)


Round 1:
Florida vs Norfolk St.: Winner: Florida
Connecticut vs Oklahoma: Winner: Oklahoma
Memphis vs Colorado St.: Winner: Memphis
Maryland vs Grand Canyon: Winner: Maryland
Missouri vs Drake: Winner: Missouri
UNC Wilmington vs Kansas: Winner: Kansas
Arkansas vs St. John's: Winner: St. John's
Texas Tech vs Nebraska Omaha: Winner: Texas Tech
Round 2:
Florida vs Oklahoma: Winner: Florida
Memphis vs Maryland: Winner: Maryland
Missouri vs Kansas: Winner: Kansas
St. John's vs Texas Tech: Winner: Texas Tech
Round 3:
Florida vs Maryland: Winner: Florida
Kansas vs Texas Tech: Winner: Texas Tech
Round 4:
Florida vs Texas Tech: Winner: Florida
Round 5:
Winner: Florida


4-element Vector{Any}:
 Any[1, 4, 5, 7, 9, 12, 14, 15]
 Any[1, 7, 12, 15]
 Any[1, 15]
 Any[1]

In [123]:
# Add region winners
region_champs = ["Florida", "Michigan St.", "UCLA", "Wisconsin"]
final4_df = reorder_dataframe(df_test, :TEAM, region_champs)

# In Julia, we use dropmissing() instead of dropna()
final4_df = dropmissing(final4_df)

# Simulate the championship
champs = simulate_single_elimination_tournament(final4_df)

Round 1:
Florida vs Michigan St.: Winner: Michigan St.
UCLA vs Wisconsin: Winner: Wisconsin
Round 2:
Michigan St. vs Wisconsin: Winner: Michigan St.
Round 3:
Winner: Michigan St.


2-element Vector{Any}:
 Any[2, 4]
 Any[2]